---
kind: pipeline
name: "Verify and Build"

steps:
  - name: node
    image: node
    commands:
      - npm install
      - npm run build
    when:
      branch:
        exclude:
          - main

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registery_password
      repo: season28/week6_supabase_nextjs
      tags: ${DRONE_COMMIT_SHA:0:7}
